image: Visual Studio 2022


install:
  - choco install gitversion.portable -pre -y

before_build:
  - gitversion /l console /output buildserver
  - nuget restore

environment:
  pack_params: -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:PublishRepositoryUrl=true -p:EmbedUntrackedSources=true --output output -p:Configuration=Release -p:ContinuousIntegrationBuild=true
  DOCKER_USER: mvrens
  DOCKER_PASS:
    secure: ol+rFY/8BLif5lS4b/KgKvru8mjwXcaddaVkDkfXJAU=

after_build:
  # Create NuGet packages
  - dotnet pack CodeSniffer.Core\CodeSniffer.Core.csproj %pack_params% -p:Version=%GitVersion_NuGetVersion%
  # Push artifacts
  - ps: Get-ChildItem output\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem output\*.snupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  # Build and push Docker image
  - ps: docker build -t mvrens/codesniffer:$env:GitVersion_NuGetVersion -f CodeSniffer\bin\Release\net6.0\DockerFile .
  - ps: Write-Output $env:DOCKER_PASS | docker login -u="$env:DOCKER_USER" --password-stdin
  - ps: docker push mvrens/codesniffer:$env:GitVersion_NuGetVersion"
  - ps: docker logout

build:
  project: CodeSniffer.sln

platform:
  - Any CPU

configuration:
  - Release

deploy:
  - provider: NuGet
    api_key:
      secure: DWFz7brxvCOtPLGJWxMojaVzIJimMGd7BPdlW75MjbhHJuoHwG1kPxZHVdjN4tPe

    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/